name       : perl-text-roman
version    : 3.5
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SY/SYP/Text-Roman-3.5.tar.gz : cb4a08a3b151802ffb2fce3258a416542ab81db0f739ee474a9583ffb73e046a
license    : Artistic-2.0
component  : programming.perl
summary    : Allows conversion between Roman and Arabic algarisms.
description: |
    Allows conversion between Roman and Arabic algarisms.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
